'use strict';

// list of most usable http status codes
let httpCode = {
  ACCEPTED: 202,
  BAD_GATEWAY: 502,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  CONTINUE: 100,
  CREATED: 201,
  EXPECTATION_FAILED: 417,
  FAILED_DEPENDENCY: 424,
  FORBIDDEN: 403,
  GATEWAY_TIMEOUT: 504,
  GONE: 410,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  IM_A_TEAPOT: 418,
  INSUFFICIENT_SPACE_ON_RESOURCE: 419,
  INSUFFICIENT_STORAGE: 507,
  INTERNAL_SERVER_ERROR: 500,
  LENGTH_REQUIRED: 411,
  LOCKED: 423,
  METHOD_FAILURE: 420,
  METHOD_NOT_ALLOWED: 405,
  MOVED_PERMANENTLY: 301,
  MOVED_TEMPORARILY: 302,
  MULTI_STATUS: 207,
  MULTIPLE_CHOICES: 300,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
  NO_CONTENT: 204,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NOT_ACCEPTABLE: 406,
  NOT_FOUND: 404,
  NOT_IMPLEMENTED: 501,
  NOT_MODIFIED: 304,
  OK_REQUEST: 200,
  PARTIAL_CONTENT: 206,
  PAYMENT_REQUIRED: 402,
  PERMANENT_REDIRECT: 308,
  PRECONDITION_FAILED: 412,
  PRECONDITION_REQUIRED: 428,
  PROCESSING: 102,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  REQUEST_TIMEOUT: 408,
  REQUEST_TOO_LONG: 413,
  REQUEST_URI_TOO_LONG: 414,
  REQUESTED_RANGE_NOT_SATISFIABLE: 416,
  RESET_CONTENT: 205,
  SEE_OTHER: 303,
  SERVICE_UNAVAILABLE: 503,
  SWITCHING_PROTOCOLS: 101,
  TEMPORARY_REDIRECT: 307,
  TOO_MANY_REQUESTS: 429,
  UNAUTHORIZED: 401,
  UNPROCESSABLE_ENTITY: 422,
  UNSUPPORTED_MEDIA_TYPE: 415,
  USE_PROXY: 305,
};


// appropriate message for above status codes
let httpMessage = {
  [httpCode.ACCEPTED]: 'Accepted',
  [httpCode.BAD_GATEWAY]: 'Bad Gateway',
  [httpCode.BAD_REQUEST]: 'Bad Request',
  [httpCode.CONFLICT]: 'Conflict',
  [httpCode.CONTINUE]: 'Continue',
  [httpCode.CREATED]: 'Created',
  [httpCode.EXPECTATION_FAILED]: 'Expectation Failed',
  [httpCode.FAILED_DEPENDENCY]: 'Failed Dependency',
  [httpCode.FORBIDDEN]: 'Forbidden',
  [httpCode.GATEWAY_TIMEOUT]: 'Gateway Timeout',
  [httpCode.GONE]: 'Gone',
  [httpCode.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version Not Supported',
  [httpCode.IM_A_TEAPOT]: 'I\'m a teapot',
  [httpCode.INSUFFICIENT_SPACE_ON_RESOURCE]: 'Insufficient Space on Resource',
  [httpCode.INSUFFICIENT_STORAGE]: 'Insufficient Storage',
  [httpCode.INTERNAL_SERVER_ERROR]: 'Server Error',
  [httpCode.LENGTH_REQUIRED]: 'Length Required',
  [httpCode.LOCKED]: 'Locked',
  [httpCode.METHOD_FAILURE]: 'Method Failure',
  [httpCode.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [httpCode.MOVED_PERMANENTLY]: 'Moved Permanently',
  [httpCode.MOVED_TEMPORARILY]: 'Moved Temporarily',
  [httpCode.MULTI_STATUS]: 'Multi-Status',
  [httpCode.MULTIPLE_CHOICES]: 'Multiple Choices',
  [httpCode.NETWORK_AUTHENTICATION_REQUIRED]: 'Network Authentication Required',
  [httpCode.NO_CONTENT]: 'No Content',
  [httpCode.NON_AUTHORITATIVE_INFORMATION]: 'Non Authoritative Information',
  [httpCode.NOT_ACCEPTABLE]: 'Not Acceptable',
  [httpCode.NOT_FOUND]: 'Not Found',
  [httpCode.NOT_IMPLEMENTED]: 'Not Implemented',
  [httpCode.NOT_MODIFIED]: 'Not Modified',
  [httpCode.OK_REQUEST]: 'Ok Request',
  [httpCode.PARTIAL_CONTENT]: 'Partial Content',
  [httpCode.PAYMENT_REQUIRED]: 'Payment Required',
  [httpCode.PERMANENT_REDIRECT]: 'Permanent Redirect',
  [httpCode.PRECONDITION_FAILED]: 'Precondition Failed',
  [httpCode.PRECONDITION_REQUIRED]: 'Precondition Required',
  [httpCode.PROCESSING]: 'Processing',
  [httpCode.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
  [httpCode.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request Header Fields Too Large',
  [httpCode.REQUEST_TIMEOUT]: 'Request Timeout',
  [httpCode.REQUEST_TOO_LONG]: 'Request Entity Too Large',
  [httpCode.REQUEST_URI_TOO_LONG]: 'Request-URI Too Long',
  [httpCode.REQUESTED_RANGE_NOT_SATISFIABLE]: 'Requested Range Not Satisfiable',
  [httpCode.RESET_CONTENT]: 'Reset Content',
  [httpCode.SEE_OTHER]: 'See Other',
  [httpCode.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [httpCode.SWITCHING_PROTOCOLS]: 'Switching Protocols',
  [httpCode.TEMPORARY_REDIRECT]: 'Temporary Redirect',
  [httpCode.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [httpCode.UNAUTHORIZED]: 'Unauthorized',
  [httpCode.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [httpCode.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
  [httpCode.USE_PROXY]: 'Use Proxy',
};

module.exports = {
  httpCode,
  httpMessage,
};
